version: '3.4'

services:
  mongodb:
    image: mongo:latest
    restart: unless-stopped
    env_file: ./.env
    ports:
      - "27019:27019"
    volumes:
      - data:/data/db
  backend:
    image: backend
    depends_on:
      - mongodb
    build:
      context: .
      dockerfile: ./api_gate/Dockerfile
    environment:
      NODE_ENV: production
      PORT: 3001
    ports:
      - "3001:3001"
    links:
      - mongodb
    volumes:
      - .:/usr/src/index

volumes:
  data: