
export const ARHCAMP_CREATE_REQUEST="ARHCAMP_CREATE_REQUEST"
export const ARHCAMP_CREATE_SUCCESS="ARHCAMP_CREATE_SUCCESS"
export const ARHCAMP_CREATE_FAIL="ARHCAMP_CREATE_FAIL"
export const ARHCAMP_CREATE_RESET="ARHCAMP_CREATE_RESET"


export const ARHCAMP_LIST_REQUEST="ARHCAMP_LIST_REQUEST"
export const ARHCAMP_LIST_SUCCESS="ARHCAMP_LIST_SUCCESS"
export const ARHCAMP_LIST_FAIL="ARHCAMP_LIST_FAIL"


export const ARHCAMP_BYID_REQUEST="ARHCAMP_BYID_REQUEST"
export const ARHCAMP_BYID_SUCCESS="ARHCAMP_BYID_SUCCESS"
export const ARHCAMP_BYID_FAIL="ARHCAMP_BYID_FAIL"

export const ARHCAMP_CREATE_REVIEW_REQUEST="ARHCAMP_CREATE_REVIEW_REQUEST"
export const ARHCAMP_CREATE_REVIEW_SUCCESS="ARHCAMP_CREATE_REVIEW_SUCCESS"
export const ARHCAMP_CREATE_REVIEW_FAIL="ARHCAMP_CREATE_REVIEW_FAIL"
export const ARHCAMP_CREATE_REVIEW_RESET="ARHCAMP_CREATE_REVIEW_RESET"

