export const PRIJAVE_KREIRAJ_REQUEST="PRIJAVE_KREIRAJ_REQUEST"
export const PRIJAVE_KREIRAJ_SUCCESS="PRIJAVE_KREIRAJ_SUCCESS"
export const PRIJAVE_KREIRAJ_FAIL="PRIJAVE_KREIRAJ_FAIL"
export const PRIJAVE_KREIRAJ_RESET="PRIJAVE_KREIRAJ_RESET"



export const PRIJAVE_LIST_REQUEST="PRIJAVE_LIST_REQUEST"
export const PRIJAVE_LIST_SUCCESS="PRIJAVE_LIST_SUCCESS"
export const PRIJAVE_LIST_FAIL="PRIJAVE_LIST_FAIL"


export const PRIJAVE_BYID_REQUEST="PRIJAVE_BYID_REQUEST"
export const PRIJAVE_BYID_SUCCESS="PRIJAVE_BYID_SUCCESS"
export const PRIJAVE_BYID_FAIL="PRIJAVE_BYID_FAIL"

export const PRIJAVE_KAMPBYID_REQUEST="PRIJAVE_KAMPBYID_REQUEST"
export const PRIJAVE_KAMPBYID_SUCCESS="PRIJAVE_KAMPBYID_SUCCESS"
export const PRIJAVE_KAMPBYID_FAIL="PRIJAVE_KAMPBYID_FAIL"

export const PRIJAVE_KORISNICI_REQUEST="PRIJAVE_KORISNICI_REQUEST"
export const PRIJAVE_KORISNICI_SUCCESS="PRIJAVE_KORISNICI_SUCCESS"
export const PRIJAVE_KORISNICI_FAIL="PRIJAVE_KORISNICI_FAIL"


export const PRIJAVE_DELETE_REQUEST="PRIJAVE_DELETE_REQUEST"
export const PRIJAVE_DELETE_SUCCESS="PRIJAVE_DELETE_SUCCESS"
export const PRIJAVE_DELETE_FAIL="PRIJAVE_DELETE_FAIL"
export const PRIJAVE_DELETE_RESET="PRIJAVE_DELETE_RESET"

export const CREATE_OCENA_REQUEST="CREATE_OCENA_REQUEST"
export const CREATE_OCENA_SUCCESS="CREATE_OCENA_SUCCESS"
export const CREATE_OCENA_FAIL="CREATE_OCENA_FAIL"
export const CREATE_OCENA_RESET="CREATE_OCENA_RESET"

export const DELETE_OCENA_REQUEST="DELETE_OCENA_REQUEST"
export const DELETE_OCENA_SUCCESS="DELETE_OCENA_SUCCESS"
export const DELETE_OCENA_FAIL="DELETE_OCENA_FAIL"
export const DELETE_OCENA_RESET="DELETE_OCENA_RESET"

export const PRIJAVE_ZAKAMP_REQUEST="PRIJAVE_ZAKAMP_REQUEST"
export const PRIJAVE_ZAKAMP_SUCCESS="PRIJAVE_ZAKAMP_SUCCESS"
export const PRIJAVE_ZAKAMP_FAIL="PRIJAVE_ZAKAMP_FAIL"