export const NOVOST_LIST_REQUEST="NOVOST_LIST_REQUEST"
export const NOVOST_LIST_SUCCESS="NOVOST_LIST_SUCCESS"
export const NOVOST_LIST_FAIL="NOVOST_LIST_FAIL"



export const NOVOST_BYID_REQUEST="NOVOST_BYID_REQUEST"
export const NOVOST_BYID_SUCCESS="NOVOST_BYID_SUCCESS"
export const NOVOST_BYID_FAIL="NOVOST_BYID_FAIL"


export const NOVOST_DELETE_REQUEST="NOVOST_DELETE_REQUEST"
export const NOVOST_DELETE_SUCCESS="NOVOST_DELETE_SUCCESS"
export const NOVOST_DELETE_FAIL="NOVOST_DELETE_FAIL"

export const NOVOST_CREATE_REQUEST="NOVOST_CREATE_REQUEST"
export const NOVOST_CREATE_SUCCESS="NOVOST_CREATE_SUCCESS"
export const NOVOST_CREATE_FAIL="NOVOST_CREATE_FAIL"
export const NOVOST_CREATE_RESET="NOVOST_CREATE_RESET"
